### ISSUE TITLE
请问大佬重构了嘛

### ISSUE THREAD

**Issue by ghost** [ParrotSec-CN/ParrotSecCN_Community_QQbot#2]
请问大佬重构了嘛

**Comment by TrojanAZhen** [comment]
**目前已合并到** [master](https://github.com/ParrotSec-CN/ParrotSecCN_Community_QQbot) **分支，改成了Python3，修改了逻辑**

**Comment by White-Code-Byte** [comment]
很高兴您能发现我的小站，目前网站还在重构。个人开发，渗透大佬清高抬贵手。志趣相同之人也可以一起交流。

from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
Date:2024/07/16 02:13:44
***@***.***>
***@***.***>
Theme:Re: [ParrotSec-CN/ParrotSecCN_Community_QQbot] 请问大佬重构了嘛 (#2)

Closed #2 as completed.
